global using FluentValidation.Results;
global using Acquirer.Sample.Domain.Entities;
global using Acquirer.Sample.Domain.Enums;
global using Acquirer.Sample.Domain.Extensions;
global using Acquirer.Shared.Messages;
global using System;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
