global using Microsoft.EntityFrameworkCore;
global using Acquirer.Sample.Domain.Entities;
global using Acquirer.Sample.Domain.Enums;
global using Acquirer.Sample.Infrastructure.Persistence;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
